# This is a basic workflow to help you get started with Actions

name: Static HTML Deployment to Ubuntu Server

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
     
      # # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

  test:
    runs-on: ubuntu-latest
    steps:
      
      - name: Run a one-line script
        run: echo 'This is test'

  deployment:
    runs-on: ubuntu-latest
    steps:

      - name: Check out the code
        uses: actions/checkout@v3

      - name: Present working directory
        run: |
          pwd
          ls -la

      - name: ssh-scp-deploy
        uses: marcodallasanta/ssh-scp-deploy@v1.2.0
        with:
          local: 'index.html'
          remote: '~/index.html'
          host: ${{secrets.HOST}}
         # port: ${{secrets.PORT}}
          user: ${{secrets.USER}}
          password: ${{secrets.PASSWORD}} 
          key: ${{secrets.KEY}}
          pre_upload: sudo rm -rf /var/www.html/index.html
          post_upload: sudo mv ~/index.html /var/www/html/index.html
          ssh_options: -o StrictHostKeyChecking=no